name: Build Game Installers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Windows executable
        run: python build.py

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-game
          path: dist/TheInversePath.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Linux executable
        run: python build.py

      - name: Upload Linux build
        uses: actions/upload-artifact@v4
        with:
          name: linux-game
          path: dist/TheInversePath
